[theme]
primaryColor="#111111"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f7f7f7"
textColor="#202124"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
